version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE_NAME: cafeConn
      MYSQL_USER_NAME: root
      MYSQL_ROOT_PASSWORD:


networks:
  web:
    driver: bridge