version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cafeConn
      MYSQL_USER_NAME: root
      MYSQL_ROOT_PASSWORD:
    volumes:
      - /db:/var/lib/mysql

networks:
  web:
    driver: bridge
