import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/Fragments/Navbar";
import {Container} from "@/components/Fragments/Container";
import {Footer} from "@/components/Fragments/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav>
        <Navbar/>
      </nav>
      <main style={{
        paddingTop: "64px",
      }}>
        <Container>
          {children}
        </Container>
      </main>
      <footer>
        <Footer/>
      </footer>
      </body>
      </html>
  );
}
