go get cloud.google.com/go/storage
go get github.com/midtrans/midtrans-go
go get github.com/iancoleman/strcase
go get github.com/nfnt/resize
go get googlemaps.github.io/maps
go get cloud.google.com/go
go get github.com/go-sql-driver/mysql
go get golang.org/x/oauth2
go get github.com/go-redis/redis_rate/v10
go get github.com/vikram1565/request-ip
go get github.com/google/uuid
go get github.com/sirupsen/logrus
go get github.com/gorilla/mux
go get github.com/golang-jwt/jwt/v5
go get github.com/redis/go-redis/v9
go get gopkg.in/yaml.v3
go get github.com/robfig/cron/v3@v3.0.0
go get github.com/joho/godotenv
go get github.com/aws/aws-sdk-go/aws
go get github.com/aws/aws-sdk-go-v2
go get github.com/rs/cors
go get github.com/aws/aws-sdk-go/aws/awsutil@v1.55.7
go get github.com/segmentio/kafka-go